name: Build Gojiboard52

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: zmkfirmware/zmk-dev-arm:stable

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Build Left Half Firmware
      run: |
        west init -l app
        west update
        west build -s zmk/app -d build/left -b nice_nano_v2 -- -DSHIELD=gojiboard52_touch_left

    - name: Build Right Half Firmware
      run: |
        west build -s zmk/app -d build/right -b nice_nano_v2 -- -DSHIELD=gojiboard52_touch_right

    - name: Upload Left Half Artifact
      uses: actions/upload-artifact@v2
      with:
        name: firmware-left
        path: build/left/zephyr/zmk.uf2

    - name: Upload Right Half Artifact
      uses: actions/upload-artifact@v2
      with:
        name: firmware-right
        path: build/right/zephyr/zmk.uf2
