name: Build ZMK Firmware for Split Keyboard

on:
  push:
    branches:
      - main
    paths:
      - 'app/**'
      - '.github/workflows/build-gojib.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker.io/zmkfirmware/zmk-build-arm:3.2

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache west modules
        uses: actions/cache@v3.0.2
        with:
          path: |
            modules/
            tools/
            zephyr/
            bootloader/
          key: ${{ runner.os }}-build-${{ hashFiles('app/west.yml') }}

      - name: Initialize workspace (west init)
        run: west init -l app

      - name: Update modules (west update)
        run: west update

      - name: Export Zephyr CMake package (west zephyr-export)
        run: west zephyr-export

      - name: Build Firmware for gojiboard52_touch Left
        run: west build -s app -b nice_nano_v2 -- -DSHIELD=gojiboard52_touch_left

      - name: Archive Left Firmware Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: firmware-left
          path: |
            build/zephyr/*.uf2
            build/zephyr/*.hex

      - name: Build Firmware for gojiboard52_touch Right
        run: west build -s app -b nice_nano_v2 -- -DSHIELD=gojiboard52_touch_right
        working-directory: .
      
      - name: Archive Right Firmware Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: firmware-right
          path: |
            build/zephyr/*.uf2
            build/zephyr/*.hex
